// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydleuumyxxdoyqgtbbwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkbGV1dW15eHhkb3lxZ3RiYndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTM1NTAsImV4cCI6MjA3MDcyOTU1MH0.J4JTU0CDWkuNJiYnPnfQFd0Eaz-vvcIWHeqJHlbZ0bQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});